ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'REFUND';
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "stock_restored" BOOLEAN NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS "ProductCostHistory" (
  id BIGSERIAL PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  purchase_price DECIMAL(15,2) NOT NULL,
  date TIMESTAMP(3) NOT NULL DEFAULT now()
);
